### PR TITLE
Don't return :ns for namespace or import completions

### PR DESCRIPTION
**Pull request by cichli**
See clojure-emacs/cider#995

### CODE REVIEW

**Comment by cichli** [comment]
Also added a tweak to return a `:type` of `:class` instead of `:import` for candidates like `goog.ui.IdGenerator`. I think class is a better terminology here.

**Comment by cichli** [comment]
I've added completion for keywords from the analyzer constant table. Happy to make a separate PR but it's less effort to merge this way :+1:.

**Comment by cichli** [comment]
@gtrak ping :-)

**Comment by gtrak** [comment]
nice! will deploy a new snapshot.  You're tracking the cider stuff pretty closely I'm assuming, how far out is it from a stable release?

**Comment by cichli** [comment]
Well it's up to @bbatsov when a release happens :-). But I've been using this patch with 0.9.0-SNAPSHOT without any problems so far.

**Comment by bbatsov** [comment]
I'm hoping to release 0.9 by the end of the month.

**Pull request merged**
