### PR TITLE
Elide :anonymous defs from completions

### PR DESCRIPTION
**Pull request by cichli**
`reify` creates anonymous type symbols, which are included in completion results:

Since [this commit](https://github.com/clojure/clojurescript/commit/2fa939bb3bb8c90ac0567db2b5dd2ad87dc1f3ae#diff-b64165608bed8fb21a132890b4e2fca2R637) these now have `:anonymous` metadata.

Example metadata and the actual source location:

```edn
{:protocol-inline nil,
 :protocols #{cljs.core/IMeta cljs.core/IDeref cljs.core/IWithMeta},
 :name cljs.core.async.impl.channels/->t27832,
 :variadic false,
 :file
 "file:/Users/griffithsm/.m2/repository/org/clojure/core.async/0.1.346.0-17112a-alpha/core.async-0.1.346.0-17112a-alpha.jar!/cljs/core/async/impl/channels.cljs",
 :method-params ([val box meta27833]),
 :protocol-impl nil,
 :arglists-meta (nil nil),
 :anonymous true,
 :column 3,
 :factory :positional,
 :methods
 ({:tag cljs.core.async.impl.channels/t27832,
   :variadic false,
   :max-fixed-arity 3}),
 :line 17,
 :max-fixed-arity 3,
 :fn-var true,
 :arglists '([val box meta27833]),
 :skip-protocol-flag
 #{cljs.core/IMeta cljs.core/IDeref cljs.core/IWithMeta},
 :test true}
```

```clojure
...
(defn box [val]
  (reify cljs.core/IDeref
    (-deref [_] val)))
...
```

With the patch applied, all better:

### CODE REVIEW

**Comment by cichli** [comment]
I had to remove the openjdk6 target from Travis since the clojurescript dep was updated - the bundled version of closure compiler now requires JDK 1.7+.

**Comment by gtrak** [comment]
That's great news! I'll check it out soon and cut a release for cider's
sake.

**Comment by bbatsov** [comment]
Nice improvement!

**Comment by bbatsov** [comment]
@gtrak How about that new release? :-)

**Comment by gtrak** [comment]
@bbatsov v0.1.4 released!

**Comment by bbatsov** [comment]
@gtrak Thanks!

Btw, maybe you should make @cichli a co-maintainer of the package? It's always better for important packages to have a couple of maintainers IMO. The chances of everyone being busy at the same time lessen significantly this way. :-)

**Comment by gtrak** [comment]
Yea, been considering it. Well the reason I didn't do it right away this
time was due to trying to make separate tests for different cljs versions,
but I ended up backing those out.

**Comment by cichli** [comment]
> separate tests for different cljs versions

I've thought about this too but it can get messy once the tests themselves need to change (like they would in this case). I think the best thing to do is just hold out for 1.0 (which at the current rate of development seems like it will be sooner rather than later). It's not a perfect situation but right now I'd say that people are expected to have latest(ish) cljs + latest(ish) tools if they want things to work. Maybe we could just have test profiles for each of the last 5 releases or something.

Thankfully we've not been affected by all the recent tool breakage but we may be once the AST is canonicalised to the tools.analyzer format, which David tells me is one of the two remaining blockers for 1.0 (the other is a port of clojure.pprint).

**Comment by cichli** [comment]
Oh and regarding co-maintainership - I don't really mind :-). Any non-trivial changes I'd probably rather go through a PR still just to get another set of eyes to at least glance over it.

**Comment by gtrak** [comment]
Yea, cool.  I'm happy to try to keep more on top of it, definitely don't
want to block @bbatsov's releases.  I don't see immediately how to let
multiple people deploy to clojars, I think ideally I'd want travis-ci to do
it for me.

**Comment by bbatsov** [comment]
The UI is kind of dumb - go to your clojar's profile and click on the project's group. There you can add other people who can update the package.

**Pull request merged**
